// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvxw9o26pLPrGUgIBBMAxIDQSHPHi-pDg',
    appId: '1:77231598009:web:4af1c7f7160a46a19cee68',
    messagingSenderId: '77231598009',
    projectId: 'orion-d1229',
    authDomain: 'orion-d1229.firebaseapp.com',
    storageBucket: 'orion-d1229.firebasestorage.app',
    measurementId: 'G-NY9P2F4T6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgw0KhZXd_IiO7TmEwRk5euASbg8YK2RM',
    appId: '1:77231598009:android:4bb04093e4bb2e3b9cee68',
    messagingSenderId: '77231598009',
    projectId: 'orion-d1229',
    storageBucket: 'orion-d1229.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxYs6ST-Qey9aZn5AI4_dhY6s7ZEzN3no',
    appId: '1:77231598009:ios:f1c14e2933fa084f9cee68',
    messagingSenderId: '77231598009',
    projectId: 'orion-d1229',
    storageBucket: 'orion-d1229.firebasestorage.app',
    iosBundleId: 'com.example.orion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxYs6ST-Qey9aZn5AI4_dhY6s7ZEzN3no',
    appId: '1:77231598009:ios:f1c14e2933fa084f9cee68',
    messagingSenderId: '77231598009',
    projectId: 'orion-d1229',
    storageBucket: 'orion-d1229.firebasestorage.app',
    iosBundleId: 'com.example.orion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvxw9o26pLPrGUgIBBMAxIDQSHPHi-pDg',
    appId: '1:77231598009:web:80a4f68b1a3df5d69cee68',
    messagingSenderId: '77231598009',
    projectId: 'orion-d1229',
    authDomain: 'orion-d1229.firebaseapp.com',
    storageBucket: 'orion-d1229.firebasestorage.app',
    measurementId: 'G-EQES4F0GJ8',
  );
}
