name: Flutter Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  analyze_and_unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test -r expanded

  android_integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - run: flutter pub get
      - name: Run on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: default
          profile: Nexus 6
          script: flutter test integration_test -r expanded
      - name: Upload integration screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration_screenshots
          path: |
            build/integration_test/**/screenshots/**/*
            build/integration_test/screenshots/**/*

  build_apk:
    runs-on: ubuntu-latest
    needs: [analyze_and_unit, android_integration]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - run: flutter pub get
      - run: flutter build apk --debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: orion-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Orion Debug APK v${{ github.run_number }}
          body: |
            Automated debug APK build for Orion project.

            ## Changes
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref }}

            ## Download
            Download the APK from the artifacts below.
          draft: false
          prerelease: true
